---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  namespace: knative-eventing
  name: knative-eventing
spec: {}
