# https://www.ibm.com/docs/en/cloud-paks/cp-waiops/3.1.1?topic=installing-postinstallation-tasks
---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-evt-group
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: TARGET_NAMESPACE
              value: "{{.Values.metadata.argocd_app_namespace}}"
            - name: WAIT_TIME
              value: "{{.Values.metadata.post_install_wait}}"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x

              # https://pages.github.ibm.com/up-and-running/watson-aiops/AI_Manager/Installation/#ngnix-certificate-for-v31

              result=0
              ingress_secret_name=$(oc get ingresscontroller.operator default \
                      --namespace openshift-ingress-operator \
                      -o jsonpath='{.spec.defaultCertificate.name}')
              if [ -n "${ingress_secret_name}" ]; then
                  echo "INFO: Retrieving default ingress certificate." \
                  && cert=$(oc get secret "${ingress_secret_name}" \
                      --namespace openshift-ingress \
                      -o jsonpath='{.data.tls\.crt}') \
                  && cert_key=$(oc get secret "${ingress_secret_name}" \
                      --namespace openshift-ingress \
                      -o jsonpath='{.data.tls\.key}') \
                  && oc get secret default-ssl -n "${TARGET_NAMESPACE}" -o yaml \
                  && echo "INFO: Patching default-ssl certificate with ingress certificate." \
                  && oc patch secret default-ssl \
                      --namespace "${TARGET_NAMESPACE}"  \
                      --type=merge -p \
                      "{\"data\": { \"cert.crt\": \"${cert}\", \"cert.key\": \"${cert_key}\"}}" \
                  && echo "INFO: Restarting foundational services nginx pods." \
                  && oc rollout restart Deployment/ibm-nginx \
                      --namespace "${TARGET_NAMESPACE}" \
                  && oc rollout status Deployment/ibm-nginx \
                      --namespace "${TARGET_NAMESPACE}" \
                  || result=1
              else
                  log "INFO: No default ingress set for the cluster."
              fi

              exit ${result}

              ca_crt=$(base64 -w0 < "${PKI_PATH}/ca/intermediate/certs/intermediate.cert.pem")
              oc patch secret external-tls-secret \
                      --namespace "${TARGET_NAMESPACE}" \
                      --type=merge -p \
                      "{\"data\": { \"ca.crt\": \"${ca_crt}\", \"cert.crt\": \"${cert}\", \"cert.key\": \"${cert_key}\"}}"
                      # --from-literal=ca.crt="${ca_crt}" \
                      # --from-literal=tls.crt="${cert}" \
                      # --from-literal=tls.key="${cert_key}


              exit "${result}"

      restartPolicy: Never
      serviceAccountName: {{.Values.serviceaccount.argocd_application_controller}}
  backoffLimit: 1
